language: go

go:
  - 1.4
  - 1.5
  - 1.6
  - tip

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

install:
  - # Do nothing.

script:
  - go get -t -v ./...
  - go test -v -cover -race ./...
  - diff -u <(echo -n) <(gofmt -d -s .)
  - go vet ./...
